import { canonicalDomainOpenApi } from './modules/domain/domain.openapi';

export const openApiDocument = {
  openapi: '3.0.3',
  info: { title: 'MN25 Mineral Intelligence API', version: '1.0.0', description: 'Unified, organization-scoped MN25 backend with provenance and auditability.' },
  servers: [{ url: '/api' }],
  components: { securitySchemes: { sessionCookie: { type: 'apiKey', in: 'cookie', name: 'mn25_session' } } },
  security: [{ sessionCookie: [] }],
  paths: {
    '/auth/register': { post: { summary: 'Register an organization/user' } },
    '/auth/login': { post: { summary: 'Create an authenticated session' } },
    '/auth/logout': { post: { summary: 'Revoke the current session' } },
    '/auth/refresh': { post: { summary: 'Rotate the current session' } },
    '/auth/me': { get: { summary: 'Return authenticated user and permissions' } },
    '/datasets': { get: { summary: 'List organization datasets' }, post: { summary: 'Create an immutable dataset version' } },
    '/datasets/{id}/validate': { post: { summary: 'Validate a dataset asynchronously' } },
    '/datasets/{id}/process': { post: { summary: 'Process a dataset asynchronously' } },
    '/models': { get: { summary: 'List registered models' } },
    '/ml/train': { post: { summary: 'Queue spatially validated prospectivity training; blocked until dataset readiness is READY' } },
    '/ml/models': { get: { summary: 'List production ML model versions' } },
    '/ml/models/{id}': { get: { summary: 'Get ML model version and training metadata' } },
    '/ml/models/{id}/promote': { post: { summary: 'Admin-only model lifecycle promotion' } },
    '/ml/experiments': { get: { summary: 'List ML experiments' } },
    '/ml/predict': { post: { summary: 'Queue prediction using a PRODUCTION model and registered feature stack' } },
    '/ml/predictions/{id}': { get: { summary: 'Get prediction and full provenance' } },
    '/ml/predictions/{id}/explanation': { get: { summary: 'Get model explanation output' } },
    '/ml/predictions/{id}/uncertainty': { get: { summary: 'Get uncertainty/applicability/data-quality' } },
    '/ml/predictions/{id}/map': { get: { summary: 'Get prediction geometry and map artifacts' } },
    '/models/{id}/versions': { get: { summary: 'List model versions' } },
    '/analyses': { post: { summary: 'Queue an analysis' } },
    '/domain/analyses/{id}/provenance': canonicalDomainOpenApi.paths['/api/domain/analyses/{id}/provenance'].get,
    '/domain/predictions/{id}/provenance': canonicalDomainOpenApi.paths['/api/domain/predictions/{id}/provenance'].get,
    '/reports': { get: { summary: 'List traceable reports' }, post: { summary: 'Queue report generation' } },
    '/actions': { get: { summary: 'List operational actions' }, post: { summary: 'Create an action plan' } },
    '/risks': { get: { summary: 'List organization risks' } },
    '/production/history': { get: { summary: 'List authoritative production records' } },
  },
};
