import { Router } from 'express';
import { Queue } from 'bullmq';
import fs from 'fs/promises';
import path from 'path';
import { requireAuth, requirePermission, requireRole } from '../../middleware/auth';
import { prisma } from '../../lib/prisma';
import { env } from '../../config/env';
import { AppError } from '../../middleware/errorHandler';
import { recordAudit } from '../audit/audit.service';

export const mlRouter = Router();
mlRouter.use(requireAuth);
const mlQueue = new Queue('ml-jobs', { connection: { url: env.redisUrl } });
function dataRoot() { return process.env.MN25_DATA_ROOT ?? path.resolve(process.cwd(), '../data'); }
function readinessPath() { return process.env.MN25_DATA_READINESS_REPORT ?? path.join(dataRoot(), 'reports/dataset_readiness/DATASET_READINESS_REPORT.md'); }
async function readinessStatus() { try { const text=await fs.readFile(readinessPath(),'utf8'); return text.includes('Overall status: **READY**')?'READY':'BLOCKED'; } catch { return 'UNAVAILABLE'; } }

mlRouter.post('/train', requireRole('ADMIN'), async (req,res,next)=>{ try {
  const readiness=await readinessStatus(); if(readiness!=='READY') throw new AppError(409,'training_blocked','TRAINING BLOCKED — DATASET INVALID. The authoritative dataset readiness report is not READY. No model training was started.');
  const datasetVersion=typeof req.body?.datasetVersion==='string'?req.body.datasetVersion:null; const featureVersion=typeof req.body?.featureVersion==='string'?req.body.featureVersion:null;
  if(!datasetVersion||!featureVersion) throw new AppError(400,'invalid_request','datasetVersion and featureVersion are required.');
  const experiment=await prisma.mLExperiment.create({data:{organizationId:req.user!.organizationId,createdByUserId:req.user!.id,name:typeof req.body?.name==='string'?req.body.name:`MN25 prospectivity experiment ${new Date().toISOString()}`,datasetVersion,featureVersion,modelType:'PROSPECTIVITY_CLASSIFICATION',hyperparameters:req.body?.hyperparameters??{},randomSeed:Number(req.body?.randomSeed??20260925),trainingBlocks:[],validationBlocks:[],testBlocks:[],status:'QUEUED',codeVersion:process.env.MN25_ML_CODE_VERSION??'mn25-ml-1.0.0'}});
  await mlQueue.add('train-prospectivity',{experimentId:experiment.id}); await recordAudit({organizationId:req.user!.organizationId,userId:req.user!.id,action:'ml.training.requested',resourceType:'MLExperiment',resourceId:experiment.id,metadata:{datasetVersion,featureVersion}}); res.status(202).json({experimentId:experiment.id,status:'queued'});
} catch(e){next(e);} });

mlRouter.get('/models', requirePermission('ml.read'), async(req,res,next)=>{try{const versions=await prisma.modelVersion.findMany({where:{type:'PROSPECTIVITY',model:{OR:[{organizationId:null},{organizationId:req.user!.organizationId}]}},orderBy:{releasedAt:'desc'},include:{model:true}});res.json({results:versions.map(v=>({id:v.id,modelId:v.modelId,name:v.name,version:v.version,algorithm:v.algorithm,datasetVersion:v.datasetVersion,featureVersion:v.featureVersion,status:v.mlStatus,deploymentStatus:v.status,metrics:v.metrics,calibration:v.calibration,artifactLocation:v.artifactLocation,trainingDate:v.trainingDate,deploymentDate:v.deploymentDate}))});}catch(e){next(e);}});

mlRouter.get('/models/:id', requirePermission('ml.read'), async(req,res,next)=>{try{const v=await prisma.modelVersion.findFirst({where:{id:req.params.id,type:'PROSPECTIVITY',model:{OR:[{organizationId:null},{organizationId:req.user!.organizationId}]}},include:{model:true,mlTrainingRuns:true}});if(!v)throw new AppError(404,'not_found','ML model version not found.');res.json({id:v.id,modelId:v.modelId,name:v.name,version:v.version,purpose:v.description,algorithm:v.algorithm,status:v.mlStatus,deploymentStatus:v.status,datasetVersion:v.datasetVersion,featureVersion:v.featureVersion,metrics:v.metrics,calibration:v.calibration,hyperparameters:v.hyperparameters,uncertaintyMethod:v.uncertaintyMethod,applicabilityMethod:v.applicabilityMethod,artifactLocation:v.artifactLocation,trainingDate:v.trainingDate,deploymentDate:v.deploymentDate,trainingRuns:v.mlTrainingRuns});}catch(e){next(e);}});

mlRouter.get('/experiments', requirePermission('ml.read'), async(req,res,next)=>{try{const rows=await prisma.mLExperiment.findMany({where:{organizationId:req.user!.organizationId},orderBy:{createdAt:'desc'},include:{trainingRuns:true}});res.json({results:rows});}catch(e){next(e);}});
mlRouter.get('/experiments/:id', requirePermission('ml.read'), async(req,res,next)=>{try{const row=await prisma.mLExperiment.findFirst({where:{id:req.params.id,organizationId:req.user!.organizationId},include:{trainingRuns:true}});if(!row)throw new AppError(404,'not_found','ML experiment not found.');res.json(row);}catch(e){next(e);}});

mlRouter.post('/predict', requirePermission('analysis.run'), async(req,res,next)=>{try{const modelVersionId=typeof req.body?.modelVersionId==='string'?req.body.modelVersionId:null;if(!modelVersionId||!req.body?.geometry)throw new AppError(400,'invalid_request','modelVersionId and GeoJSON geometry are required.');const model=await prisma.modelVersion.findFirst({where:{id:modelVersionId,type:'PROSPECTIVITY',mlStatus:'PRODUCTION',status:'DEPLOYED',model:{OR:[{organizationId:null},{organizationId:req.user!.organizationId}]}}});if(!model)throw new AppError(409,'model_not_available','No production prospectivity model version is available for this organization.');const datasetVersion=typeof req.body?.datasetVersion==='string'?req.body.datasetVersion:model.datasetVersion;const featureVersion=typeof req.body?.featureVersion==='string'?req.body.featureVersion:model.featureVersion;if(!datasetVersion||!featureVersion)throw new AppError(409,'input_data_unavailable','The production model has no registered dataset/feature version.');const run=await prisma.mLPredictionRun.create({data:{organizationId:req.user!.organizationId,requestedByUserId:req.user!.id,modelVersionId,datasetVersion,featureVersion,geometry:req.body.geometry,status:'QUEUED',analysisJobId:typeof req.body?.analysisJobId==='string'?req.body.analysisJobId:undefined}});await mlQueue.add('predict-prospectivity',{predictionRunId:run.id});await recordAudit({organizationId:req.user!.organizationId,userId:req.user!.id,action:'ml.prediction.requested',resourceType:'MLPredictionRun',resourceId:run.id,metadata:{modelVersionId,datasetVersion,featureVersion}});res.status(202).json({predictionRunId:run.id,status:'queued'});}catch(e){next(e);}});

mlRouter.get('/predictions/:id', requirePermission('ml.read'), async(req,res,next)=>{try{const p=await prisma.prediction.findFirst({where:{id:req.params.id,organizationId:req.user!.organizationId},include:{model:true,modelVersion:true,datasetVersions:{include:{datasetVersion:{include:{dataset:true}}}}}});if(!p)throw new AppError(404,'not_found','Prediction not found.');const geo=await prisma.$queryRaw<Array<{geojson:string|null}>>`SELECT ST_AsGeoJSON("geometry") AS geojson FROM "Prediction" WHERE "id"=${p.id}`;res.json({predictionId:p.id,model:{id:p.model.id,name:p.model.name},modelVersion:{id:p.modelVersion.id,version:p.modelVersion.version,algorithm:p.modelVersion.algorithm,metrics:p.modelVersion.metrics},inputDatasetVersions:p.datasetVersions.map(x=>({id:x.datasetVersion.id,dataset:x.datasetVersion.dataset.name,version:x.datasetVersion.version,checksum:x.datasetVersion.checksum,role:x.role})),geometry:geo[0]?.geojson?JSON.parse(geo[0].geojson):null,prediction:p.prediction,uncertainty:p.uncertainty,applicability:p.applicability,dataQuality:p.dataQuality,featureVersion:p.featureVersion,sourceSceneIds:p.sourceSceneIds,explanation:p.explainability,generatedAt:p.generatedAt,status:p.status});}catch(e){next(e);}});
mlRouter.get('/predictions/:id/explanation', requirePermission('ml.read'), async(req,res,next)=>{try{const p=await prisma.prediction.findFirst({where:{id:req.params.id,organizationId:req.user!.organizationId},select:{explainability:true,modelVersion:{select:{version:true,name:true}}}});if(!p)throw new AppError(404,'not_found','Prediction not found.');res.json({model:p.modelVersion.name,modelVersion:p.modelVersion.version,explanation:p.explainability??null});}catch(e){next(e);}});
mlRouter.get('/predictions/:id/uncertainty', requirePermission('ml.read'), async(req,res,next)=>{try{const p=await prisma.prediction.findFirst({where:{id:req.params.id,organizationId:req.user!.organizationId},select:{uncertainty:true,applicability:true,dataQuality:true,status:true}});if(!p)throw new AppError(404,'not_found','Prediction not found.');res.json(p);}catch(e){next(e);}});
mlRouter.get('/predictions/:id/map', requirePermission('ml.read'), async(req,res,next)=>{try{const p=await prisma.prediction.findFirst({where:{id:req.params.id,organizationId:req.user!.organizationId},select:{id:true,modelVersion:{select:{version:true}}}});if(!p)throw new AppError(404,'not_found','Prediction not found.');const geo=await prisma.$queryRaw<Array<{geojson:string|null}>>`SELECT ST_AsGeoJSON("geometry") AS geojson FROM "Prediction" WHERE "id"=${p.id}`;res.json({predictionId:p.id,modelVersion:p.modelVersion.version,geometry:geo[0]?.geojson?JSON.parse(geo[0].geojson):null,rasterArtifact:null,vectorArtifact:null,note:'Map artifacts are available only after a validated production prediction run.'});}catch(e){next(e);}});

mlRouter.post('/models/:id/promote', requireRole('ADMIN'), async (req,res,next)=>{try{
  const target=typeof req.body?.status==='string'?req.body.status:null;
  const allowed=['REVIEW','APPROVED','PRODUCTION','RETIRED']; if(!target||!allowed.includes(target)) throw new AppError(400,'invalid_status','status must be REVIEW, APPROVED, PRODUCTION, or RETIRED.');
  const v=await prisma.modelVersion.findFirst({where:{id:req.params.id,type:'PROSPECTIVITY',model:{organizationId:req.user!.organizationId}}}); if(!v) throw new AppError(404,'not_found','Model version not found.');
  const allowedNext: Record<string,string[]>={TRAINED:['REVIEW'],VALIDATED:['REVIEW'],REVIEW:['APPROVED'],APPROVED:['PRODUCTION'],PRODUCTION:['RETIRED'],RETIRED:[]};
  if(target!=='RETIRED' && !(allowedNext[v.mlStatus] ?? []).includes(target)) throw new AppError(409,'invalid_transition',`Cannot promote model from ${v.mlStatus} to ${target}.`);
  if(target==='PRODUCTION'){
    const metrics=v.metrics; const hasMetrics=!!metrics && typeof metrics==='object' && !Array.isArray(metrics) && Object.values(metrics as Record<string,unknown>).some(x=>typeof x==='number'&&Number.isFinite(x));
    if(v.mlStatus!=='APPROVED'||!hasMetrics||!v.artifactLocation) throw new AppError(422,'promotion_blocked','Production promotion requires an APPROVED model with validation metrics and an immutable artifact.');
    await prisma.modelVersion.updateMany({where:{modelId:v.modelId,status:'DEPLOYED'},data:{status:'RETIRED',mlStatus:'RETIRED'}});
    await prisma.modelVersion.update({where:{id:v.id},data:{mlStatus:'PRODUCTION',status:'DEPLOYED',deploymentDate:new Date()}});
    if(v.modelId) await prisma.modelRegistry.update({where:{id:v.modelId},data:{status:'DEPLOYED',currentVersion:v.version,deploymentDate:new Date(),metrics:v.metrics??undefined,trainingDataset:v.trainingDataset??undefined,trainingDate:v.trainingDate??undefined,features:v.features??undefined}});
  } else {
    const map: Record<string,'REVIEW'|'APPROVED'|'RETIRED'>={REVIEW:'REVIEW',APPROVED:'APPROVED',RETIRED:'RETIRED'};
    await prisma.modelVersion.update({where:{id:v.id},data:{mlStatus:map[target],status:target==='RETIRED'?'RETIRED':v.status}});
  }
  await recordAudit({organizationId:req.user!.organizationId,userId:req.user!.id,action:'ml.model.promoted',resourceType:'ModelVersion',resourceId:v.id,metadata:{target}});
  res.json({modelVersionId:v.id,status:target});
}catch(e){next(e);}});
