'use client';
import { useEffect, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, Download, FileText, History, Search, ShieldCheck, SlidersHorizontal, Trash2, Eye } from 'lucide-react';
import type { Zone } from '../../lib/data';
import { createReport, deleteReport, getReportDownloadUrl, getReportPreview, getReports, type BackendReport, type ReportSection, type ReportType } from '../../lib/api';

type SubjectType='analysis'|'region'|'mine'|'hotspot';
const labels:Record<ReportType,string>={quick:'Quick Exploration Report',detailed:'Detailed Exploration Report',prospectivity:'AI Prospectivity Report'};
const subjects:Record<SubjectType,string>={analysis:'Current Analysis',region:'Selected Region',mine:'Mining Area',hotspot:'AI Hotspot'};
const sections:[ReportSection,string][]=[['summary','Executive Summary'],['maps','Location & Maps'],['mining','Mining Information'],['geology','Geological Profile'],['ai','AI Prospectivity'],['spectral','Spectral Analysis'],['model','Model Insights'],['sources','Data Sources'],['limits','Limitations']];
const defaults=(t:ReportType)=>new Set<ReportSection>(t==='quick'?['summary','maps','mining','ai','sources']:t==='prospectivity'?['summary','maps','ai','spectral','model','sources','limits']:sections.map(x=>x[0]));
const API_BASE = process.env.NEXT_PUBLIC_API_BASE || 'http://localhost:4000';

export default function ReportsWorkspace({zones,selectedZoneId='A'}:{zones:Zone[];selectedZoneId?:string}){
 const [history,setHistory]=useState<BackendReport[]>([]),[mode,setMode]=useState<'history'|'create'|'preview'>('history'),[subject,setSubject]=useState<SubjectType>('region'),[type,setType]=useState<ReportType>('detailed'),[zoneId,setZoneId]=useState(selectedZoneId),[chosen,setChosen]=useState<Set<ReportSection>>(defaults('detailed')),[q,setQ]=useState(''),[preview,setPreview]=useState<string|null>(null),[previewData,setPreviewData]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 const zone=useMemo(()=>zones.find(z=>z.id===zoneId)||zones[0],[zones,zoneId]);
 const loadHistory=async()=>{try{const r=await getReports({q:q||undefined,limit:50});setHistory(r.results);setError(null);}catch(e){setHistory([]);setError(e instanceof Error?e.message:'Unable to load reports.');}};
 useEffect(()=>{loadHistory();},[]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{if(mode==='history'){const id=window.setTimeout(loadHistory,250);return()=>window.clearTimeout(id);}},[q,mode]); // eslint-disable-line react-hooks/exhaustive-deps
 const selectedSubjectId=zone?.id || zoneId;
 const toggle=(id:ReportSection)=>setChosen(s=>{const n=new Set(s);n.has(id)?n.delete(id):n.add(id);return n});
 const create=async()=>{if(!selectedSubjectId)return;setBusy(true);setError(null);try{const created=await createReport({subjectType,subjectId:selectedSubjectId,reportType:type,sections:[...chosen],analysisIds:[]});const id=created.reportId;for(let i=0;i<60;i++){const r=await new Promise<BackendReport>(async(resolve,reject)=>{try{resolve(await (await import('../../lib/api')).getReport(id));}catch(e){reject(e);}});if(r.status==='READY'){setHistory(h=>[r,...h.filter(x=>x.id!==r.id)]);setPreview(id);setMode('preview');await loadPreview(id);return;}if(r.status==='FAILED')throw new Error(r.errorMessage||'Report generation failed.');await new Promise(res=>setTimeout(res,1000));}}catch(e){setError(e instanceof Error?e.message:'Report generation failed.');}finally{setBusy(false);}};
 const loadPreview=async(id:string)=>{try{const p=await getReportPreview(id);setPreviewData(p);setError(null);}catch(e){setError(e instanceof Error?e.message:'Report preview unavailable.');}};
 const openReport=async(id:string)=>{setPreview(id);setMode('preview');setError(null);await loadPreview(id);};
 const download=async(id:string)=>{try{const r=await getReportDownloadUrl(id);window.open(`${API_BASE}${r.url}`,'_blank','noopener,noreferrer');}catch(e){setError(e instanceof Error?e.message:'Download unavailable.');}};
 const remove=async(id:string)=>{if(!confirm('Delete this report from history?'))return;try{await deleteReport(id);await loadHistory();}catch(e){setError(e instanceof Error?e.message:'Unable to delete report.');}};
 if(mode==='create') return <div className="page-fade reports-workspace">
  <div className="reports-topline"><div><span className="eyebrow"><FileText size={12}/> REPORT BUILDER</span><h2>Create exploration report</h2><p className="sub">Reuse existing MN25 analysis context; unsupported facts are not invented.</p></div><button className="btn" onClick={()=>setMode('history')}><ArrowLeft size={14}/> History</button></div>
  {error&&<div className="report-trust-strip"><ShieldCheck size={17}/><div><b>Report generation notice</b><span>{error}</span></div></div>}
  <div className="report-stepper"><span className="active"><b>1</b> Subject</span><i/><span className="active"><b>2</b> Type</span><i/><span className="active"><b>3</b> Content</span><i/><span><b>4</b> Preview</span></div>
  <div className="two">
   <section className="card"><div className="section-title"><h2>1. Select subject</h2><span className="pill">Existing data</span></div><div className="choice-grid">{(Object.keys(subjects) as SubjectType[]).map(k=><button key={k} className={`choice-card ${subject===k?'selected':''}`} onClick={()=>setSubject(k)}><b>{subjects[k]}</b><span>Reuse available MN25 context</span></button>)}</div><div className="control" style={{marginTop:16}}><label>Region / mining area</label><select className="select" value={zone?.id} onChange={e=>setZoneId(e.target.value)}>{zones.map(z=><option key={z.id} value={z.id}>{z.name} · {z.region}</option>)}</select></div></section>
   <section className="card"><div className="section-title"><h2>2. Select report type</h2></div><div className="stack">{(['quick','detailed','prospectivity'] as ReportType[]).map(k=><button key={k} className={`report-type ${type===k?'selected':''}`} onClick={()=>{setType(k);setChosen(defaults(k))}}><div><b>{labels[k]}</b><span>{k==='quick'?'Fast overview.':k==='detailed'?'Evidence-rich exploration summary.':'Focused AI prospectivity report.'}</span></div>{type===k&&<Check size={16}/>}</button>)}</div></section>
  </div>
  <section className="card report-content-card"><div className="section-title"><div><h2>3. Report content</h2><p className="sub">Sections without valid data will be explicitly marked unavailable.</p></div><SlidersHorizontal size={17}/></div><div className="report-section-grid">{sections.map(([id,label])=><label className="report-check" key={id}><input type="checkbox" checked={chosen.has(id)} onChange={()=>toggle(id)}/><span>{label}</span></label>)}</div><div className="report-builder-footer"><span className="data-tag">Evidence-first reporting</span><button className="btn primary" disabled={busy||chosen.size===0} onClick={create}>{busy?'Generating…':'Generate Preview'} {!busy&&<ArrowRight size={14}/>}</button></div></section>
 </div>;
 if(mode==='preview'){
  const c=previewData?.content; const r=history.find(x=>x.id===preview); const title=previewData?.title||r?.title||'MN25 Report';
  return <div className="page-fade reports-workspace"><div className="reports-topline no-print"><div><span className="eyebrow"><Eye size={12}/> REPORT PREVIEW</span><h2>{title}</h2><p className="sub">{r?.subjectType||previewData?.content?.subjectType} · {previewData?.reportId||preview}</p></div><div className="actions-row"><button className="btn" onClick={()=>setMode('history')}><ArrowLeft size={14}/> History</button><button className="btn primary" disabled={!r||r.status!=='READY'} onClick={()=>preview&&download(preview)}><Download size={14}/> Download PDF</button></div></div>
   {error&&<div className="report-trust-strip"><ShieldCheck size={17}/><div><b>Report notice</b><span>{error}</span></div></div>}
   {!c?<div className="card report-empty"><b>Preparing report preview…</b><span>The validated report snapshot is being loaded.</span></div>:<article className="report-paper"><header className="report-cover"><div className="mn25-wordmark"><span>MN</span><em>25</em></div><span className="eyebrow">EXPLORATION INTELLIGENCE REPORT</span><h1>{title}</h1><h2>{(previewData.analysisSnapshot as any)?.subject?.region||'Selected MN25 subject'}</h2><div className="report-meta-grid"><span>Generated<b>{new Date(c.generatedAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</b></span><span>Report ID<b>{previewData.reportId}</b></span><span>Version<b>v{previewData.version}</b></span></div></header>
   {(c.sections||[]).map((s:any)=><section className="report-section" key={s.id}><h3>{s.title}</h3>{s.paragraphs?.map((p:string,i:number)=><p key={i}>{p}</p>)}{s.rows&&<div className="report-table">{s.rows.map((row:[string,string],i:number)=><div key={i}><span>{row[0]}</span><b>{row[1]}</b></div>)}</div>}{s.bullets&&<ul>{s.bullets.map((b:string,i:number)=><li key={i}>{b}</li>)}</ul>}</section>)}
   <footer className="report-footer">MN25 · {previewData.reportId} · Version {previewData.version} · Evidence preserved from the generated analysis snapshot.</footer></article>}
  </div>
 }
 return <div className="page-fade reports-workspace"><div className="reports-topline"><div><span className="eyebrow"><FileText size={12}/> REPORTS</span><h2>Exploration intelligence & reporting</h2><p className="sub">Generate, review, preserve and download traceable exploration reports.</p></div><button className="btn primary" onClick={()=>setMode('create')}><FileText size={14}/> Create New Report</button></div>
 {error&&<div className="report-trust-strip"><ShieldCheck size={17}/><div><b>Report service notice</b><span>{error}</span></div></div>}
 <div className="report-history-toolbar card"><div className="search"><Search size={15}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search reports, regions or analysis IDs..." /></div><span className="pill"><History size={12}/> {history.length} reports</span></div>
 <div className="section-title"><h2>Report History</h2><span className="data-tag">Saved analysis context</span></div><div className="report-history-grid">{history.map(r=><article className="card report-history-card" key={r.id}><div className="row"><span className="pill">{r.status}</span><span className="footer-note">{new Date(r.createdAt).toLocaleDateString('en-GB',{day:'2-digit',month:'short',year:'numeric'})}</span></div><h3>{r.title}</h3><p className="sub">{r.subjectType} · {r.subjectId}</p><div className="report-history-meta"><span>Analysis<br/><b>{labels[r.reportType]}</b></span><span>Version<br/><b>{r.currentVersion?`v${r.currentVersion}`:'Queued'}</b></span><span>Status<br/><b>{r.status}</b></span></div><div className="actions-row"><button className="btn small" disabled={r.status!=='READY'} onClick={()=>openReport(r.id)}><Eye size={13}/> View</button><button className="btn small" disabled={r.status!=='READY'} onClick={()=>download(r.id)}><Download size={13}/> Download</button><button className="icon-btn" onClick={()=>remove(r.id)} title="Delete report"><Trash2 size={14}/></button></div></article>)}{!history.length&&<div className="card report-empty"><History size={24}/><b>No reports found</b><span>Generate your first report from an analyzed region.</span><button className="btn primary" onClick={()=>setMode('create')}>Create Report</button></div>}</div>
 <section className="report-trust-strip"><ShieldCheck size={17}/><div><b>Evidence-first reporting</b><span>Documented facts, observations and AI predictions remain clearly separated. Unsupported values are shown as unavailable.</span></div></section></div>
}
